version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    networks:
      - jumpingkid-network
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: jumpingkid_password
      POSTGRES_USER: jumpingkid_user
      POSTGRES_DB: jumpingkid_db
    ports:
      - "5432:5432"
    networks:
      - jumpingkid-network

volumes:
  postgres-data:

networks:
  jumpingkid-network:
